### ISSUE TITLE
Add a user-facing "infeasible or unbounded" problem status; update solver interfaces

### ISSUE THREAD

**Issue by rileyjmurray** [cvxpy/cvxpy#1071]
In PR #1065 there was some discussion on how ``test_lp_3`` is failing for GUROBI on CVXPY's master branch. The issue is that under default settings, GUROBI employs a presolve feature which can make it impossible to distinguish between certificates of infeasibility and certificates of unboundedness. CPLEX apparently employs a similar presolve procedure, and currently maps "infeasible or unbounded" to ["unbounded_inaccurate"](https://github.com/cvxgrp/cvxpy/blob/c451fea281dc786dd21b1e7d58f02f3df274fa4c/cvxpy/reductions/solvers/conic_solvers/cplex_conif.py#L195-L197). The pending PR for SCIP (#1035) also maps "infeasible or unbounded" to "unbounded_inaccurate".

It's not appropriate for us to parse an "infeasible or unbounded" status into either "infeasible" or "unbounded" (with or without an "inaccurate" suffix). The most direct solutions are (1) raise a solver failure, or (2) create a new CVXPY status for this situation. Another solution is for CVXPY to automatically re-solve the problem with presolve turned off, before ever returning to the user.

It would be useful if developers of affected solvers could provide opinions on possible ways to proceed. @rluce is with GUROBI, @rkersh is with CPLEX, and @rimaddo is the SCIP contributor. Also pinging @SteveDiamond and @akshayka.

**Comment by rimaddo** [comment]
For me the deciding factor between re-solving vs making another status would be speed, i.e. can you re-solve and return the second result to the user fast enough to make it more-worthwhile than them investigating.

One thing I've done in the past to diagnose this problem is also to set the objective to 0 on the re-solve, that way if there is _any_ feasible solution it will return it much more quickly and you know it's unbounded, or otherwise infeasible. Could it also help in this case?

**Comment by akshayka** [comment]
My vote is for (2), a new status (eg, INFEASIBLE_UNBOUNDED). It’s a simple solution, requires minimal code change, and with the right documentation, it’ll be easy for users to understand.

In the website documentation describing this status, we can give tips on how to diagnose whether the problem is infeasible or unbounded (like rimaddo’s tip above). These tips might be specialized for different solvers.

That said: if the alternative of re-solving can be shown to be reliable and not too slow (say, no longer than the original solve), and if someone wants to do the work of implementing, testing, and maintaining it, that could work too.

**Comment by rkersh** [comment]
@rileyjmurray, I'm no longer employed with IBM. In the future, can you please work with @djunglas (Daniel Junglas) for CPLEX related issues. I've forwarded this issue to him via email as well. Thanks!

**Comment by rluce** [comment]
+1 for making it a proper cvxpy status. From a user perspective an infeasible or unbounded solution status very often points in fact to a modeling error, and it doesn't really matter which of the two it is.

**Comment by SteveDiamond** [comment]
I vote for making a INFEASIBLE_UNBOUNDED cvxpy status. I wanted to mention that the gurobi conic interface currently resolves when it gets "infeasible or unbounded", so that should be changed.

**Comment by rileyjmurray** [comment]
It seems there's a general consensus around adding a new status. I'm happy to go that route as well.
