### ISSUE TITLE
Setting variable bounds (domain?)

### ISSUE THREAD

**Issue by adishavit** [cvxpy/cvxpy#1106]
Bounded variables are very common (LB <= var  <= UB). 
Some have internal bounds like `nonneg` And `boolean` and for others, one needs to add the bound constraints. For example an integer variable cannot be specified to be nonneg. 

When linearizing various formulations (eg big-M methods) one needs to pass around big M bounds in addition to the bound constraints. 
This is inconvenient and makes interfaces cumbersome. 

Is there some place that these bounds are stored within a Leaf, Variable or Atom?
I saw something called domain. 
Is that relevant?

**Comment by rileyjmurray** [comment]
We currently don't have such a feature. You just append ``LB <= var`` and ``var <= UB`` to the list of constraints.

Right now CVXPY doesn't treat domain constraints differently than expression constraints. For example, ``x = Variable(nonneg=True)`` is later replaced by ``y = Variable(),  y >= 0`` when CVXPY prepares data for a solver. This sort of conversion isn't ideal because it means solvers can't exploit efficient methods for bound constraints. I'm personally in favor of changing this so that domain information is processed in a specialized way. However, there is currently no timeline for adding such a feature.

Maybe you're asking about something else, though?

**Comment by adishavit** [comment]
Thanks. That was the question.

The API I was hoping for was something conceptually like having
`lower_bound` and `upper_bound` members or properties which can be set and
queried.

When you have these coupled to the variable they be used in eg big-M
constraints and also no need to add them explicitly to the constraints
(they will be added automatically like with booleans).

**Comment by SteveDiamond** [comment]
Clarifying for people who may work on this, step 1 is to add support for a ``bounds`` attribute to Variables and Parameters. After that is implemented we can look into passing bounds information directly to the solvers.

**Comment by jonathanberthias** [comment]
To add my 2 cents, I don't think adding `bounds` to the variable is a great API gain, as `x >= 0` is easier to understand and more general.
What I think could be really useful is if CVXPY were able to infer some variable bounds from the constraints without having to explicitly use the `bounds` attribute. So that e.g. `x <= 3` can be interpreted as a domain constraint and not just like any other constraint. That information can then be passed to the underlying solver.

**Comment by SteveDiamond** [comment]
@jonathanberthias I have worked now with OR people and they consider ``bounds`` an important part of the API. Adding automatic checks for variable bounds is an interesting idea but not something we intend to add because it would increase the compile time, which is a major concern for many users.

**Comment by SteveDiamond** [comment]
Closed by #2234
