### ISSUE TITLE
DCP rules and diagonal submatrices

### ISSUE THREAD

**Issue by tschm** [cvxpy/cvxpy#1213]
Hello,
We all know how to maximize

`
mu' x - r * x' Cov x.
`

Here mu is a vector of expected returns, r is a parameter for risk-aversion (nonneg=True) and Cov is PSD covariance matrix. There is also what's called a concentration which is x' cvx.diag(cvx.diag(Cov)) x. So I am using only the diagonal entries of Cov. Note that this matrix will be PSD if Cov is PSD. Nevertheless, cvxpy fails with DCP problems. How would I approach this problem? manz thanks...

**Comment by phschiele** [comment]
Hi @tschm!
Perhaps it helps to add a reproducible example to talk about, so lets consider this optimization from the [portfolio optimization notebook](https://colab.research.google.com/github/cvxgrp/cvx_short_course/blob/master/applications/portfolio_optimization.ipynb):

```python
# Generate data for long only portfolio optimization.
import numpy as np
import cvxpy as cp

np.random.seed(1)
n = 10
mu = np.abs(np.random.randn(n, 1))
Sigma = np.random.randn(n, n)
Sigma = Sigma.T.dot(Sigma)

w = cp.Variable(n)
gamma = cp.Parameter(nonneg=True)
gamma.value = 1
ret = mu.T@w 
risk = cp.quad_form(w, Sigma)
concentration = cp.quad_form(w, cp.diag(cp.diag(Sigma)))
prob = cp.Problem(cp.Maximize(ret - gamma*risk - concentration), 
               [cp.sum(w) == 1, 
                w >= 0])
prob.solve()
```
Indeed, this fails due to the DCP error you mentioned.
However, changing `cp.diag(cp.diag(Sigma))` to `np.diag(np.diag(Sigma))` already solves the issue.

What would also work is passing the `value` of the first `diag` function to the second one:
`cp.diag(cp.diag(Sigma).value)`

```python
diag1 = cp.diag(Sigma)
print(diag1.is_psd())
diag2 = cp.diag(diag1.value)
print(diag2.is_psd())
>> True
>> True
#####
diag1 = cp.diag(Sigma)
print(diag1.is_psd())
diag2 = cp.diag(diag1)
print(diag2.is_psd())
>> True
>> False
```

It seems to build down to the implementation of `is_nonneg` in the `diag_mat` class.
As indicated in the docs (see screenshot below), `diag_mat` returns the same sign as `X` (in our case `Sigma`). Since `Sigma` contains negative (off-diagonal) elements, `is_nonneg()` returns `False`, even if only nonnegative elements are on the diagonal.
Would be interesting to hear other thoughts on this. 

![image](https://user-images.githubusercontent.com/44360364/107083617-3395c080-67f6-11eb-9de7-e4c6934fb3d6.png)

**Comment by SteveDiamond** [comment]
@phschiele very on point discussion. The sign analysis in cvxpy could always be extended further. I'm not sure if this particular cases justifies adding further sign logic.

**Comment by phschiele** [comment]
@SteveDiamond Thanks for the swift feedback. Of course, distinguishing the sign would add complexity, and in this case, the changes required to make it work with the existing implementation were rather small. 
If other cases come up where it is not as easy to fix, perhaps one can think about extending the class (or distinguish in the Docs which statements hold by definition and which ones are a simplification).

**Comment by SteveDiamond** [comment]
I would support modifying ``is_nonneg`` to check for PSDness. I wouldn't change the docs though. I'd rather have simpler docs and not explain every corner case.

**Comment by phschiele** [comment]
@SteveDiamond I have modified `is_nonneg` locally to make the code in the issue work (while not breaking existing tests). If you think it makes sense, I'd be happy to open a PR for it. It would look something like this:
```python
def is_nonneg(self):
    """Is the expression nonnegative?
    """
    if self.args[0].value is not None:
        return np.all(np.diag(self.args[0].value) >= 0)
    else:
        return super(diag_mat, self).is_nonneg()
```
If you think it's not worth the complexity or if you had a different approach in mind, please let me know.

**Comment by tschm** [comment]
@phschiele Many thanks for this analysis. I am currently still using Sigma and Sigma_diag as parameters to the problem.
Of course, that's somewhat ugly and a potential mismatch is totally possible. I support your modification of is_nonneg for diagonal matrices.

**Comment by SteveDiamond** [comment]
@phschiele the sign analysis has to be symbolic. so more like
```
def is_nonneg(self):
     return self.args[0].is_nonneg() or self.args[0].is_psd()
```
