### ISSUE TITLE
States unbounded, when actually infeasible

### ISSUE THREAD

**Issue by bzfmuelh** [cvxpy/cvxpy#1349]
**Describe the bug**
For some problems (GPs), infeasibility is not detected. For the following example, cvxpy (using ECOS) states that the problem is unbounded, when it should be infeasible. 

**To Reproduce**
```
import cvxpy as cvx

mu = cvx.Variable(2,pos=True,name='mu')
a = cvx.Variable((1,2),pos=True,name='a')
b = cvx.Variable(1,pos=True,name='b')
problem = cvx.Problem(cvx.Minimize(mu[0] * 0.48304589822553434 + mu[1] * 0.6666666666666666), [a[0, 0] <= 50.0, a[0, 1] <= 50.0, b[0] <= (a[0, 0] / 0.5000000000000001)**(1/2) * (a[0, 1] / 0.4999999999999999)**(1/2), 200.0 <= b[0]])
problem.solve(gp=True,solver='ECOS')
```

**Comment by rileyjmurray** [comment]
Thanks for posting, @bzfmuelh. This problem statement is strange because the objective function and constraints are over disjoint sets of variables. If you replace the objective by "minimize 1" instead of minimizing that function of ``mu``, then you get the correct result that the problem is infeasible.
```
problem = cvx.Problem(cvx.Minimize(1), [a[0, 0] <= 50.0, a[0, 1] <= 50.0, b[0] <= (a[0, 0] / 0.5000000000000001)**(1/2) * (a[0, 1] / 0.4999999999999999)**(1/2), 200.0 <= b[0]])
problem.solve(solver='ECOS', verbose=True, gp=True)

ECOS 2.0.7 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  +0.000e+00  -3.219e+00  +4e+00  1e-01  2e-01  1e+00  1e+00    ---    ---    1  0  - |  -  - 
 1  +0.000e+00  +6.917e+01  +3e-01  2e+00  1e+00  9e+01  6e-02  0.9484  9e-03   0  0  0 |  0  0
 2  +0.000e+00  +8.352e+03  +3e-03  2e+00  1e+00  8e+03  7e-04  0.9890  1e-04   0  0  0 |  0  0
 3  +0.000e+00  +7.206e+05  +4e-05  2e+00  1e+00  7e+05  8e-06  0.9890  1e-04   1  0  0 |  0  0
 4  +0.000e+00  +6.215e+07  +4e-07  2e+00  1e+00  6e+07  9e-08  0.9890  1e-04   1  0  0 |  0  0
 5  +0.000e+00  +5.372e+09  +5e-09  2e+00  1e+00  5e+09  1e-09  0.9890  1e-04   1  0  0 |  0  0

PRIMAL INFEASIBLE (within feastol=2.9e-10).
Runtime: 0.000188 seconds.
```
There is a chance that your problem, as formulated, is both primal infeasible *and* dual infeasible. That's a really rare situation but it can happen in theory. My advice would be to inspect the low-level problem data by calling ``data = problem.get_solver_data(solver='ECOS', gp=True)``.

**Comment by bzfmuelh** [comment]
Thanks a lot for the quick reply, that really helped a lot. I think you are right, the problem is primal and dual infeasible.
