### ISSUE TITLE
maximize dot product of two vectors

### ISSUE THREAD

**Issue by akhorshidi** [cvxpy/cvxpy#1372]
**Describe the bug**
Suppose we have three features and 252 samples per each feature. Here, features are returns of three different stocks. The goal is to maximize the total return, i,e, [Objective](https://i.stack.imgur.com/gr7Gn.png) and [Constraints](https://i.stack.imgur.com/eoTL9.png)

$$ \begin{array}{l}
\mathop {\max }\limits_{\bf{x}} {\mu _{{\rm{total}}}} = \mathop {\max }\limits_{\bf{x}} \{ {{\bf{x}}^T}{\bf{\mu }}\} \\
\begin{array}{*{20}{c}}
{{\rm{s}}{\rm{.t}}{\rm{.}}}&{\sum {{x_i} = 1,} }
\end{array}{x_i} > 0
\end{array} $$

**To Reproduce**

    import numpy as np
    import cvxpy as cvx;
    
    return1 = np.random.normal(loc=0.05, scale=0.25, size=252)
    return2 = np.random.normal(loc=0.01, scale=0.2, size=252)
    return3 = np.random.normal(loc= -0.05, scale=0.15, size=252)
    returns = np.array([return1, return2, return3])
    
    # number of stocks m is number of rows of returns
    m = returns.shape[0]
    
    # x variables (to be found with optimization)
    x = cvx.Variable(m)
    
    # portfolio return
    portfolio_return = cvx.multiply(returns, x)
    
    #objective function
    objective = cvx.Minimize(-portfolio_return)
    
    #constraints
    constraints = [x >= 0, sum(x) == 1]
    
    #use cvxpy to solve the objective
    cvx.Problem(objective, constraints).solve()
    
    #retrieve the weights of the optimized portfolio
    x_values = x.value
    
    print(x_values)

**Expected behavior**
My question is how to define this objective function inside a `CVXpy` optimization problem? 

**Output**
However, it returns an error:

    ValueError: Cannot broadcast dimensions  (3, 252) (3,)

When we represent `x` as `x = cvx.Variable(shape=(m,1))` we get another error `ValueError: The 'minimize' objective must resolve to a scalar.`

**Version**
 - OS: Windwos 10 with Python 3.8.8
 - CVXPY Version: 1.1.12

**Additional context**

**Comment by phschiele** [comment]
Hi @akhorshidi,

as you correctly point out, you need to have compatible dimensions when multiplying. 
If you elementwise multiply your three return series with the (broadcasted) weight vector, you get a matrix with the same dimensions as the returns.
However, when optimizing with cvxpy, you need a single (scalar) objective value, otherwise, you cant decide e.g. which of the following solutions is better `[1,2]` or `[2,1]`. Of course, you could do `cvxpy.sum(portfolio_return)`, but notice that this would be the same optimization problem as computing the mean of each time series and optimizing with respect to that (i.e. classical mean-variance optimization):
```python
returns_mean = returns.mean(axis=1)
objective = cvx.Maximize(x @ returns_mean)
```
As one typically denotes this mean vector with `mu`, this might be what is meant by the objective formulation you linked.
I assume you have some further constraints/objectives, otherwise, the solution would just be to put all of the weight in the asset with the highest mean return.

As this seems to be your first cvxpy issue, some small remarks that might be helpful to you:
- you can directly call `Maximize(x)` instead of `Minimize(-x)`
- Within the objective and constraints, it is usually better to use `cvxpy.sum()` over the builtin `sum()`
- Instead of the constraint `x>=0`, you can specify `nonneg=True` for the variable `x`, which in my experience can sometimes lead to "nicer" solutions (e.g. 0 weights being exactly zero, and not small negative numbers).

I hope this helps :)

**Comment by akhorshidi** [comment]
> 
@phschiele 
Thank you very much for your valuable comments and suggestions, it was really helpful!
