### ISSUE TITLE
Allowing non-negative integer variables

### ISSUE THREAD

**Issue by Midnighter** [cvxpy/cvxpy#1446]
**Is your feature request related to a problem? Please describe.**

I don't understand why it should not be possible to create non-negative integer variables. At the moment, this is forbidden due to the following exception being raised:

```py
counts = cp.Variable(shape=5, integer=True, nonneg=True)
```

```
ValueError: Cannot set more than one special attribute in Variable.
```

**Describe the solution you'd like**

I don't see why this should pose a problem and it would just require some special casing for the logic that raises the `ValueError`.

**Describe alternatives you've considered**

I know that I can add a constraint `counts >= 0` but `counts.sign` is `'UNKNOWN'` when it should really be `'NONNEGATIVE'`.

**Comment by SteveDiamond** [comment]
The reason we forbid this is because we project the optimal value of variables returned by the solver onto the constraints encoded in the variable attributes, and in the fully general case of arbitrary attributes this becomes another convex optimization problem (e.g., PSD + nonneg). Whereas if we restrict things to a single attribute then we have closed form solutions.

This particular combination of attributes is of course simple and could in theory be supported. But I'm not super comfortable permitting multiple attributes in some cases but not others.

**Comment by Midnighter** [comment]
Alright. Fair enough.

**Comment by rileyjmurray** [comment]
@Midnighter if you need `counts.sign == 'NONNEGATIVE`, then you could probably add a `nonneg_wrap` atom much like our `psd_wrap` atom: https://github.com/cvxpy/cvxpy/blob/master/cvxpy/atoms/affine/wraps.py.
