### ISSUE TITLE
Solving Erlang loss model problems and capacity planning related problems

### ISSUE THREAD

**Issue by Hadi2525** [cvxpy/cvxpy#1447]
Hello,

I would like to formulate a queueing network (M/M/k/k) optimization problem with the number of servers (k) as the variable in cvxpy. Since the objective function (i.e. blocking probability) is convex so I am optimistic to solve it in cvxpy, however, there is no atomic function available to help me with that.

I realize there is an example of the design of a queueing system on the [website](https://www.cvxpy.org/examples/derivatives/queuing_design.html) when the variable becomes the number of servers, then it becomes hard to solve. This problem is somewhat similar to the optimization problem (5) of [Mung Chiang's paper](https://stanford.edu/~boyd/papers/pdf/nonlin_opt_queue.pdf) with the difference here that arrival/service rates are constant and the number of servers is the optimization variables.

How is it possible to implement this problem in cvxpy?

**Comment by rileyjmurray** [comment]
Hi @Hadi2525, thanks for your question. The best place for you to ask this kind of thing is probably our GitHub discussions: https://github.com/cvxpy/cvxpy/discussions. You can also try the cvxpy Google group or StackOverflow with a cvxpy tag. GitHub issues (this platform) is more about the code itself rather than proper usage of the code.
