### ISSUE TITLE
Gurobi's optimal solution violates constraint by 0.29%

### ISSUE THREAD

**Issue by pqrz** [cvxpy/cvxpy#1457]
We are solving a large-scale MIQCQP problem:

```
Variables: 7.3K (= 3.7K as continuous + 3.6K as interger)
Objective: Linear
Constraints: 14.8K Linear Constraints + 1 Quadratic Constraint (Q matrix size = 3.7K * 3.7K)
Framework: Cvxpy (version: 1.1.13)
Solver: Gurobi (version: 9.0.3)
```

Gurobi finished optimization and returns the optimal solutions well, but those optimal variables violates the quadratic constraint by 0.014 (in percentage, its 0.29%).

Note: The violation is higher then default feasibility tolerance (=1e-6) of Gurobi.

Is there a possibility that this is due to **Cvxpy's problem transformation** (particularly, the Quadratic constraint to SOCP transformation)?

**Comment by rileyjmurray** [comment]
It is possible that this is due to cvxpy's problem transformations. One way to check is to introduce additional variables so the quadratic constraint is well-conditioned before converting to SOCP. For example, rather than ``con = cp.quad_form(x, P) + c.T @ x + d <= 0``, you could declare ``y = cp.Variable(shape=x.shape)`` and constrain ``cons = [y == M @ x,  cp.sum_squares(y) + c.T @ x + d <= 0]`` where ``M.T @ M == P``. That isn't necessarily the best way to proceed, but it should tell you if it's something to do with how we convert quadratic constraints to SOCP constraints. (Right now we convert ``cp.quad_form(x, P) + c.T @ x + d <= 0`` to ``cp.sum_squares(M @ x) + c.T @ x + d <= 0``.)

**Comment by pqrz** [comment]
We tried the above-mentioned technique for well-conditioning the constraints. 

Results: Constraint violation is indeed resolved. Hence, the constraint is now getting perfectly satisfied.

We had a few doubts:

- Does this experiment concludes that - **sometimes minor noise/information_loss occurs inadvertently during cvxpy's problem transformations**?
- If possible, could you slightly elucidate (or point to a reference) on - how technique guarantees lossless transformation? (Intent: we could permanently shift to this technique for our MIQCQP problem formulations)

**Comment by rileyjmurray** [comment]
Delighted to hear that this helped!

Regarding your questions:
 * The only information loss in cvxpy's problem transformations stems from [issues inherent with finite-precision arithmetic](https://en.wikipedia.org/wiki/Floating-point_arithmetic#Accuracy_problems). For example, the Cholesky decomposition of a positive definite matrix ``P`` is an upper-triangular matrix ``M`` so that ``P = M @ M.T`` in exact arithmetic. SciPy has a routine to compute Cholesky decompositions, but because of finite precision arithmetic, we cannot be guaranteed that ``P = M @ M.T`` exactly. Instead, we are only guaranteed that ``P`` is very close to ``M @ M.T``. It's a basic fact of numerical linear algebra that dot products between vectors of length ``n`` are only accurate to ``eps * poly(log(n))`` (where ``eps`` is machine precision and ``poly`` is some polynomial). However, the fact that my suggested reformulation worked means that this kind of approximation error is not the source of your troubles.
 * The main source of these kinds of accuracy issues stems from the fact that different measures of computing constraint violations can give very different results. GUROBI is computing constraint violations in some way that considers the SOCP form (there are a couple of ways of doing this and I don't know how GUROBI approaches it). You are computing constraint violations probably by checking elementwise violation ``max( x.T @ P @ x + c.T @ x + d,  0)``. These are bound to produce different results when the violation is positive. You can find information about different ways of computing constraint violations here: https://docs.mosek.com/modeling-cookbook/practical.html#distance-to-a-cone. If the matrix ``P`` has a high condition number then it becomes more likely that you run into these kinds of problems.
 
The idea behind my suggestion was that solvers are very good at accurately measuring violations of linear constraints. So it can help to introduce extra variables when it lets you move numerically troublesome parts of a model into linear constraints.

I'll close this GitHub issue since we understand the source of your problem. If you want to have more discussions, then you are welcome to post on the GitHub Discussions page.
