### ISSUE TITLE
Integer variables in GP

### ISSUE THREAD

**Issue by adishavit** [cvxpy/cvxpy#1590]
Is it possible to solve a mixed integer geometric program?
Currently, one can set just one attribute: either `integer=True` of `pos=True`. The latter is mandatory for GP problems.
Is there a way of somehow using integer variables in GPs despite this (other than using the as Real and rounding)?

**Comment by phschiele** [comment]
@adishavit This is currently not supported. See #1446 for details.
You can try setting only `integer=True` and add a constraint of the form `x>=0`.
As mentioned in#1446, you could add a `nonneg` wrap if you need the sign for DCP reasons.

**Comment by SteveDiamond** [comment]
@phschiele this is the first situation I've seen where the limitation of one attribute per variable is a real impediment. I'm starting to think that maybe multiple attributes should be allowed. Something to discuss in the discord.

@adishavit this is a very interesting use case! If you have too much trouble making a ``pos`` wrap feel free to DM me.

**Comment by rileyjmurray** [comment]
I remember a discussion on the GPKit repo about this kind of functionality. I'm adapting my comment https://github.com/convexengineering/gpkit/issues/414#issuecomment-582564038 to summarize:

### Constraining a variable to take on specific values in mixed-integer convex programming

Here's a function that takes a scalar variable ``y`` and returns constraints that ensure ``y.value`` is in ``vec``:
```
def varval_in_vec(y, vec):
    vec = np.sort(vec)
    d = np.diff(vec)
    z = Variable(shape=(d.size,), boolean=True)
    cons = [z[i+1] <= z[i] for i in range(d.size)]
    cons.append(y == vec[0] + d @ z)
    return cons
```
The initial constraints in ``cons`` together with 0/1 constraints on ``z`` ensure that ``z`` is always a vector of the form ``[1,...,1,0,...,0]`` -- i.e. consecutive ones, then consecutive zeros. The constraint ``y == vec[0] + d @ z`` ensures that ``y`` takes a value in ``vec``.

### Using ``varval_in_vec`` for mixed-integer geometric programming

In our context, we'll have a vector of positive integers ``a``, and we'll want to constrain a posynomial variable ``x`` to take on a value ``a[i]`` for some ``i``.  From the perspective of the mixed-integer convex programming formulation, we need to enforce constraints on ``y`` where ``y = log(x)``. Of course, ``x`` takes on a desired value as long as ``y`` takes on a value in ``vec = np.log(a)``. 

We can only use this reformulation as we're converting a DGP problem to a DCP problem. Existing code for those conversions is in [dgp2dcp/](https://github.com/cvxpy/cvxpy/tree/master/cvxpy/reductions/dgp2dcp) and especially in the subfolder [dgp2dcp/atom_canonicalizers](https://github.com/cvxpy/cvxpy/tree/master/cvxpy/reductions/dgp2dcp/atom_canonicalizers). Note that although the subfolder is called "atom_canonicalizers" it also canonicalizes Constraint objects (e.g., [here](https://github.com/cvxpy/cvxpy/blob/master/cvxpy/reductions/dgp2dcp/atom_canonicalizers/nonpos_constr_canon.py)).

### Suggested implementation route

I think the way forward here is to define a new ``Constraint`` class called ``FiniteSet``, which will basically encapsulate a call to ``varval_in_vec``. Existing Constraint classes are defined in [this folder](https://github.com/cvxpy/cvxpy/tree/master/cvxpy/constraints). Implementing the class in full generality would take a lot of work, since it applies to DCP and DGP problems. I'd be open to merging a pull request that starts by only supporting DCP problems. I also don't think the implementation for DCP problems needs to be perfect in the first pull request, so long as we have time to improve it before the release of CVXPY 1.3.

**Comment by rileyjmurray** [comment]
That's great to hear @aryamanJgl! Please feel free to follow up here with questions.

**Comment by rileyjmurray** [comment]
To clarify for those who find themselves here: the ``FiniteSet`` constraint introduced in #1740 can be used for integer variables in GP, but we haven't provided a simple function for that yet. So this issue should remain open until ``FiniteSet`` has a canonicalization pathway for DGP.

**Comment by phschiele** [comment]
Closed via #2041 which adds DGP canonicalization of `FiniteSet` as mentioned by @rileyjmurray above.

**Comment by yasirroni** [comment]
> @adishavit This is currently not supported. See #1446 for details. You can try setting only `integer=True` and add a constraint of the form `x>=0`. As mentioned in#1446, you could add a `nonneg` wrap if you need the sign for DCP reasons.

I've read the `FiniteSet` example but can't get the grasp to implement that to `cp.Variable`.

Is there any equivalent to this,

```python
v = cp.Variable((n, m), integer=True, pos=True)
``` 

without using,

```python
v = cp.Variable((n, m), integer=True)
cons = [v >=0]
```

with the help of `FiniteSet`?

**Comment by SteveDiamond** [comment]
> > @adishavit This is currently not supported. See #1446 for details. You can try setting only `integer=True` and add a constraint of the form `x>=0`. As mentioned in#1446, you could add a `nonneg` wrap if you need the sign for DCP reasons.
> 
> Hey @phschiele, I've read the `FiniteSet` example but can't get the grasp to implement that to `cp.Variable`.
> 
> Is there any equivalent to this,
> 
> ```python
> v = cp.Variable((n, m), integer=True, pos=True)
> ```
> 
> without using,
> 
> ```python
> v = cp.Variable((n, m), integer=True)
> cons = [v >=0]
> ```
> 
> with the help of `FiniteSet`?

There is not. What is the harm of 
```
v = cp.Variable((n, m), integer=True)
cons = [v >=0]
```
?
