### ISSUE TITLE
Linearized absolute value in objective is not dcp

### ISSUE THREAD

**Issue by Kreol64** [cvxpy/cvxpy#1608]
Hello,

I would like to solve a standard quadratic problem that involves an absolute value term in the objective (basically Markowitz). In order to get rid of the absolute term I linearize it by splitting into two variables: 

y = max(w-w0,0)
z = max(w0-w,0)

And then:

w=w0 + y - z and |w-w0| = y + z

cvxpy does  not have issues with (y+z) term, but for some reason it fails to pass the is_dcp() check when I use (w0 + y - z) instead of w. Example (I included only linear portion to show what the problem is):

```
import cvxpy as cp
import numpy as np

w0 = np.array([3,4,-5,6])
w = cp.Variable(4)
a = np.array([0.3, -0.8,0.1,-0.1])
c = np.array([0.01,0.03,0.02,0.05])
y = cp.maximum(w-w0, 0)
z = cp.maximum(w0-w, 0)

assert cp.Maximize(a.T @ w - c.T @ (y+z)).is_dcp()
assert cp.Maximize(a.T @ (w0 + y - z) - c.T @ (y + z)).is_dcp()
```

I actually do need to use the second option here because I later rewrite y and z as a stacked column vector to vectorize the problem. Could you please explain what am I doing wrong here and if there is a away to pass the check ? 

Thank you !

**Comment by rileyjmurray** [comment]
Hi @Kreol64, thanks for using CVXPY! The problem is cvxpy can't detect that ``a.T @ (w0 + y - z)`` is linear in ``w`` when you set ``y = cp.maximum(w-w0, 0)`` and ``z = cp.maximum(w0-w, 0)``. You should use the following instead:
```
y = cp.Variable(a.size, nonneg=True)
z = cp.Variable(a.size, nonneg=True)
objective = a.T @ w - c.T @ (y + z)
constraints = [y >= w - w0, z >= w0 - w]
```
In the future, these kinds of questions are better suited to [our Discord server](https://discord.gg/4urRQeGBCr). Please follow up there if you need additional help.

Happy optimizing!
