### ISSUE TITLE
when i install with requirements.txt cvxpy>=1.0.21,log   error in cvxpy setup command: use_2to3 is invalid.

### ISSUE THREAD

**Issue by Wangwuyi123** [cvxpy/cvxpy#1612]
**Describe the bug**

**To Reproduce**
A [minimal code example](https://stackoverflow.com/help/mcve) that reproduces the bug or unexpected behavior.

**Expected behavior**

**Output**
If applicable, include program output. If reporting a program crash, please include the entire stack trace.

**Version**
 - OS: 
 - CVXPY Version:

**Additional context**
![屏幕截图 2022-01-24 155212](https://user-images.githubusercontent.com/51237097/150742692-cd1703b9-3a9c-481a-86a3-a17321f00ad9.png)

**Comment by phschiele** [comment]
@Wangwuyi123 the title of the issue says you are trying to install `cvxpy>=1.0.21`, but in the screenshot, it shows `cvxpy==1.0.21`. Allowing for more recent versions would likely fix the issue. 

If you need the exact version there are some workarounds you could try, but I suggest trying to upgrade first.

**Comment by rileyjmurray** [comment]
Hi @Wangwuyi123. I've changed the title of your issue based on Phillipp's comment. My guess is that changing to only require ``cvxpy>=1.0.21`` will fix your issue. I especially encourage you to upgrade to cvxpy 1.1 as well, since we don't offer installation support for cvxpy 1.0.x anymore. Please post here again if you run into trouble with cvxpy 1.1!
