### ISSUE TITLE
Reminder about  #1709

### ISSUE THREAD

**Issue by keithbriggs** [cvxpy/cvxpy#1773]
Two months ago in issue #1709 (Solving a fractional linear boolean problem) I reported what looks like serious bugs in the SCIP and CBC interfaces.   I don't think anyone has looked at this yet.   I have a workaround (namely, restricting myself to GLPK_MI), but for the sake of the rest of the cvxpy community, I think these need fixing.

(Reminder: SCIP prints repeated warning messages on every iteration, and CBC returns non-boolean solution vectors.)

**Comment by rileyjmurray** [comment]
Thanks for following up, @keithbriggs. You're correct that the cvxpy community deserves to have these fixed.

PR #1739 handles SCIP. Note that part of the SCIP issue was cvxpy's SCIP interface, while another part was SCIP itself. 

When you say SCS, I think you mean CBC. @SteveDiamond @phschiele @akshayka could you look into CBC? The script that @keithbriggs provided in #1709 is very nice and clearly shows that CBC isn't respecting integrality constraints. This might be a problem in CBC, but it might also be a problem in how the CBC interface is interacting with DQCP (I don't know if that's possible because I don't know anything about the DQCP canonicalization code path). We should figure out the CBC issue ASAP and then release CVXPY 1.3.1 and the next version of 1.2.X.

**Comment by SteveDiamond** [comment]
I installed cvxpy from source and Cbc via ``pip install cylp``. The code in #1709 worked fine for me. This is on mac with Python 3.10.

**Comment by phschiele** [comment]
Thanks @keithbriggs for the nice testing script! 
CBC also works for me under Python 3.8, Ubuntu 20.04, CVXPY master, and `cylp==0.91.5`

**Comment by keithbriggs** [comment]
Thanks everyone for checking this.   I did `pip install --upgrade cylp` and the non-boolean problem went away, but was replaced by 

```
  File "/home/kbriggs/.local/lib/python3.8/site-packages/cvxpy/reductions/solvers/conic_solvers/cbc_conif.py", line 184, in solve_via_data
    solution["status"] = self.STATUS_MAP_MIP[status]
KeyError: 'problem proven infeasible'
```

However, reinstalling cvxpy from source fixed everything!    In fact, on my problems, GLPK_MI is about 20 times faster than CBC, and 10 times faster than SCIP.  So I don't really need CBC.

**Comment by SteveDiamond** [comment]
@rileyjmurray could we deploy a new patch? I'm not sure how the process works at this point...

**Comment by rileyjmurray** [comment]
@SteveDiamond I'll create a GitHub Discussion for the next patch releases (1.1.20 and 1.2.1) and tag you. I just finished updating the release/1.1.x and release/1.2.x branches so you should just be able to follow the directions in ``PROCEDURES.md``.

**Comment by SteveDiamond** [comment]
All related issues are addressed in the latest patch (deployed to pypi).
