### ISSUE TITLE
Example : select top N from array

### ISSUE THREAD

**Issue by eromoe** [cvxpy/cvxpy#1812]
**Is your feature request related to a problem? Please describe.**

I have a model to predict customer ltv ( called `pltv`), and we want to find a best cutoff of  `pltv` to select customers with condition
- sum of revenue from top n customer, higher is better.  
	-  `objective = cp.Maximize(cp.sum_largest( revenue[ y_pred >= cut] , n))`
- mean roi of top n customer, higher  is better ( which at least greater than 1.1)
    -  `constraints = [ n >0 , cp.mean(roi[ y_pred >= cut]) > 1.1 ]`

Sample code: 

```python

import cvxpy as cp
import numpy as np
import scipy.stats as st

# Problem data.

t = 100
np.random.seed(1)
y_pred = st.norm.rvs(1, 0.5 , size=t)
roi = st.norm.rvs(1, 0.5 , size=t)
revenue = st.halfnorm.rvs(0, 0.5 , size=t)

n = cp.Variable(1)
cut = cp.Variable(1)

# Construct the problem.
objective = cp.Maximize(cp.sum_largest( revenue[ (y_pred > cut)] , n))
constraints = [ n >0 , cp.mean(roi[ y_pred >= cut]) > 1.1 ]
prob = cp.Problem(objective, constraints)

result = prob.solve()

print(x.value)

print(constraints[0].dual_value)
```

**Describe the solution you'd like**

The problem is `revenue` is `numpy.array` ,  which doesn't support `cvxpy.Variable`  cut .  

```
<ipython-input-5-1acc60ebf5d7> in <module>
     21 
     22 # Construct the problem.
---> 23 objective = cp.Maximize(cp.sum_largest( revenue[ y_pred >= cut] , n))
     24 constraints = [ n >0 , cp.mean(roi[ y_pred >= cut]) > 1.1 ]
     25 prob = cp.Problem(objective, constraints)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

```

So I think there may be an option `select top N from array` , but I don't find it on document.

**Comment by phschiele** [comment]
Hi @eromoe !
There are a couple of issues with the code:
1. you can't slice numpy arrays using cvxpy variables. Generally, you should use numpy functions for data and cvxpy functions/classes for everything that depends on variables.
2. `sum_largest` is a convex function, i.e., you can only minimize it, not maximize it.
3. the second argument of `sum_largest` must be an integer, not a variable. 
4. strict inequalities are not supported, i.e., use `>=` instead of `>`.
5. `x` is not defined in the penultimate line.

Here is a quick rewrite close to your original implementation:
```py
import cvxpy as cp
import numpy as np
import scipy.stats as st

# Problem data.

t = 100
np.random.seed(1)
y_pred = st.norm.rvs(1, 0.5, size=t)
roi = st.norm.rvs(1, 0.5, size=t)
revenue = st.halfnorm.rvs(0, 0.5, size=t)

cut = cp.Variable(nonneg=True)
z = cp.Variable(t, boolean=True)
n = cp.Parameter()

# Construct the problem.
objective = cp.Maximize(cp.sum(cp.multiply(revenue, z)))
constraints = [
    cp.sum(cp.multiply(roi, z)) >= 1.1 * cp.sum(z),
    y_pred - cut >= cp.multiply(z, y_pred),
    cp.sum(z) <= n
]
prob = cp.Problem(objective, constraints)

for n_val in range(1, t + 1):
    n.value = n_val
    prob.solve()

    print(prob.status)
    print(objective.value)
```
Notice that the indicator is a boolean variable. While the above problem is still solved very quickly, it means that it might not scale well to larger problem instances. If you are wondering about the second constraint, it is referred to as "implication of positivity" and you can read more about it [here](https://docs.mosek.com/modeling-cookbook/mio.html#implication-of-positivity).
If you need to scale to bigger problem instances, you will most likely find that approximations without boolean variables will work decently and are much easier to solve.

**Comment by eromoe** [comment]
Thank you very much .
I was so busy yesterday that didn't reply inmediately. It's very kind of you to provide an dedicated example ! I would follow your recommendation to study it.

**Comment by SteveDiamond** [comment]
Feel free to reopen if you have more questions.
