### ISSUE TITLE
Why `sum_largest` does not follow DCP rules?

### ISSUE THREAD

**Issue by SightVanish** [cvxpy/cvxpy#1939]
Here is my code
```
import numpy as np
import time
import cvxpy as cp
n = 20

a = np.random.randint(1, 10, size=n)
b = np.random.randint(1, 10, size=n)
c = np.random.randint(1, 10, size=n)
d = np.random.randint(1, 10, size=n)

x = cp.Variable(shape=n, boolean=True)

# objective function 
objective = cp.Maximize(cp.sum(cp.multiply(x, a)))

# constraints
constraints = []

constraints.append(\
    cp.sum_largest(cp.hstack([\
        cp.sum(cp.multiply(x, b)), \
        cp.sum(cp.multiply(x, c)), \
        cp.sum(cp.multiply(x, d))]), 1) >= 10)


prob = cp.Problem(objective, constraints)

# solve model
prob.solve(solver=cp.CBC, verbose=True, maximumSeconds=100, numberThreads=4)
print("status:", prob.status)

```
I have solved model with `sum_largest` successfully before, so I wonder why this happened?

I am working on `python==3.6`, `ubuntu20.04`, `cvxpy==1.1.20`, `cylp==0.91.5`.

What should I do?

**Comment by aszekMosek** [comment]
Because it is convex and you are trying to use it as if it were concave. ``sum_largest<=10`` is convex, but ``sum_largest>=10`` is not.

**Comment by SightVanish** [comment]
> Because it is convex and you are trying to use it as if it were concave. `sum_largest<=10` is convex, but `sum_largest>=10` is not.

Tks for ur reply. It does work well with `sum_largest<=` but how can I add constraints like `sum_largest>=` (as this function is not convex, is there any substitute?)

**Comment by rsemenoff** [comment]
I'm having the same thing. It may be that you have to accept that your problem is just so nonlinear that you need to look at a nonlinear solver. 
One thought I had is based on the observation that a function might not be convex (if that's what you want) globally, but might be so piecewise and you have to find the bounds of that. At this point it's not clear to me that DCP takes that into account already (clearly I have some homework to do there) ...my thinking is that a nonlinear solver will have done a few iterations in the time it will take you to formulate your problem as DCP...
