### ISSUE TITLE
Same hashes for different mosek parameters

### ISSUE THREAD

**Issue by EmJay276** [cvxpy/cvxpy#2023]
**Describe the bug**
I am using cvxpy with the mosek solver.
When I try to pass `mosek.dparam.intpnt_tol_dfeas` and `mosek.iparam.intpnt_solve_form` as keys to a python dict it results in a dict with just one entry. The hashes of `mosek.dparam.intpnt_tol_dfeas` and `mosek.iparam.intpnt_solve_form` are the same!

```
mosek_params={mosek.dparam.intpnt_tol_dfeas: (1.0e-8 / length.max()), 
              mosek.iparam.intpnt_solve_form: mosek.solveform.dual}
```

Result

```
>>> mosek_params
{intpnt_tol_dfeas: dual}
```

Hashes
```
>>> hash(mosek.dparam.intpnt_tol_dfeas)
28
>>> hash(mosek.iparam.intpnt_solve_form)
28
```

**To Reproduce**
```
mosek_params={mosek.dparam.intpnt_tol_dfeas: 1.0e-8), 
              mosek.iparam.intpnt_solve_form: mosek.solveform.dual}
```
Result
```
>>> mosek_params
{intpnt_tol_dfeas: dual}
```

**Expected behavior**
```
mosek_params={mosek.dparam.intpnt_tol_dfeas: 1.0e-8), 
              mosek.iparam.intpnt_solve_form: mosek.solveform.dual}
```
Result
```
>>> mosek_params
{intpnt_tol_dfeas: 1.0e-8, intpnt_solve_form: dual}
```

**Version**
 - OS: Windows 10
 - CVXPY Version: 1.3.0

**Additional context**
The hash values are probably unique (I haven't checked all) within `mosek.iparam` and `mosek.dparam` but not across them.

I personally think this is a mosek issue and should be fixed there, I already reported it https://github.com/MOSEK/Tutorials/issues/5
A workaround would be to separate `iparam` and `dparam` in different dicts for cvxpy
```
mosek_params={'dparam': {mosek.dparam.intpnt_tol_dfeas: 1.0e-8)}, 
              'iparam': {mosek.iparam.intpnt_solve_form: mosek.solveform.dual}}
```
Or to use the string version
```
mosek_params = {'MSK_DPAR_INTPNT_TOL_DFEAS': 1.0e-8,
                'MSK_IPAR_INNTPNT_SOLVE_FORM': mosek.solveform.dual}
```
Currently this can lead to unexpected behaviour. 
I my case I luckily gut an error due to MSK_IPAR_INNTPNT_SOLVE_FORM does not accept a float), otherwise I would have never noticed and would have gotten weird results.

**Comment by SteveDiamond** [comment]
Wow, thanks for finding this issue!

**Comment by phschiele** [comment]
@EmJay276 Wow, that is indeed weird behaviour!
The reason is that the mosek python package defines these parameters as  instances of a **custom** `Enum` class:
```py
dparam = Enum("dparam",
              ["ana_sol_infeas_tol", ..., "intpnt_tol_dfeas", ..., "upper_obj_cut_finite_trh"],
              [0, ..., 28, ..., 60])

iparam = Enum("iparam",
              ["ana_sol_basis",  ..., "intpnt_solve_form", ..., "write_xml_mode"],
              [0, ..., 28, ..., 186])
```
You just happened to choose two parameters that map to the same integer, and thus have the same hash.

Note that this does not happen using the built-in Enum:
```py
from enum import Enum

class dparam(Enum):
    ana_sol_infeas_tol = 0
    intpnt_tol_dfeas = 28
    upper_obj_cut_finite_trh = 60


class iparam(Enum):
    ana_sol_basis = 0
    intpnt_solve_form = 28
    write_xml_mode = 186

hash(dparam.intpnt_tol_dfeas), hash(iparam.intpnt_solve_form)
>>> (6755082268264580700, -2215516079503337131)
```

The built-in Enum class was only introduced in Python 3.4, which might explain why it wasn't used.
You should raise this to the mosek team, perhaps @aszekMosek can give you a pointer.

**Comment by EmJay276** [comment]
@phschiele Ah nice to know, I will report it to the mosek team.
Can you send me the link to the mosek python package source? I havn't found it (yet) therefore couldn't dig into the issue further.

**Comment by phschiele** [comment]
@EmJay276 I don't think the source is open source. I just used the "go to source" feature in my IDE.

**Comment by aszekMosek** [comment]
It is not an error for the Mosek interface because in Mosek you can never use an iparam and dparam in the same place. Moreover it is not possible to get wrong results: if there is no clash then it works as expected. It is also possible to use string names (although only for names, not values). Maybe Mosek will use built-in enums one day, but this is the kind of change for a major release and not a minor fix.

As a way out of this historical mess I suggest moving completely to string names. I can make a PR that:

* raises a deprecation warning when 'iparam', 'dparam', 'sparam' appear
* handles string names of parameters and string values properly (fx. ``mosek_params={'MSK_IPAR_PRESOLVE_USE':'MSK_PRESOLVEMODE_FREE'}`` ie. allows a string on the RHS of a parameter
* adapt documentation accordingly

Strictly speaking the user of ``cvxpy`` does not have to ``import mosek`` and generic string names are nowadays clearly stated in Mosek C documentation so it sounds reasonable to use them.

Let me know if that makes sense.

**Comment by SteveDiamond** [comment]
> It is not an error for the Mosek interface because in Mosek you can never use an iparam and dparam in the same place. Moreover it is not possible to get wrong results: if there is no clash then it works as expected. It is also possible to use string names (although only for names, not values). Maybe Mosek will use built-in enums one day, but this is the kind of change for a major release and not a minor fix.
> 
> As a way out of this historical mess I suggest moving completely to string names. I can make a PR that:
> 
> * raises a deprecation warning when 'iparam', 'dparam', 'sparam' appear
> * handles string names of parameters and string values properly (fx. `mosek_params={'MSK_IPAR_PRESOLVE_USE':'MSK_PRESOLVEMODE_FREE'}` ie. allows a string on the RHS of a parameter
> * adapt documentation accordingly
> 
> Strictly speaking the user of `cvxpy` does not have to `import mosek` and generic string names are nowadays clearly stated in Mosek C documentation so it sounds reasonable to use them.
> 
> Let me know if that makes sense.

I guess using string names is the only solution here. It's too bad because I liked the mosek enums...

**Comment by EmJay276** [comment]
@aszekMosek is it possible to implement a __hash__ method for the custom `Enum` class to return unique values?
This would be the easiest fix.

`id` seems to be unique for iparam and dparam

```python
def __hash__(self):
    return id(self)
```

**Comment by EmJay276** [comment]
Without `__hash__`
```python
>>> hash(mosek.iparam.ana_sol_print_violated)
1
>>> id(mosek.iparam.ana_sol_print_violated)
1921887689664
```

Add `__hash__` method
```python
def hash_from_id(self):
    return id(self)

import mosek
mosek.EnumBase.__hash__ = hash_from_id
```

With `__hash__`
```python
>>> hash(mosek.iparam.ana_sol_print_violated)
1921887689664
>>> id(mosek.iparam.ana_sol_print_violated)
1921887689664
```

**Comment by aszekMosek** [comment]
@EmJay276 Thanks for the suggestion. Many solutions are possible but not until the next Mosek major release, and it will not retrospectively fix cvxpy for older Mosek versions. I have in the meantime made #2029 open for discussion.

**Comment by SteveDiamond** [comment]
Fixed
