### ISSUE TITLE
SDP Problem Reduction High Memory Use for MOSEK

### ISSUE THREAD

**Issue by cohnt** [cvxpy/cvxpy#2051]
**Describe the bug**
Solving a large SDP requires a very large amount of memory to set up in MOSEK, in comparison to other methods such as SCS. For a 150x150 semidefinite matrix variable, MOSEK requires several GB of memory during problem compilation, whereas SCS uses virtually none.

**To Reproduce**
```
import numpy as np
import cvxpy

n = 150
np.random.seed(43)
Q = np.random.normal(loc=0, scale=1, size=(n,n))

X = cvxpy.Variable((n,n), symmetric=True)
constraints = [X[i,i] == 1 for i in range(n)] + [X >> 0]
objective = cvxpy.Minimize(cvxpy.trace(Q @ X))
problem = cvxpy.Problem(objective, constraints)
problem.solve(verbose=True, solver=cvxpy.SCS)
```
Replacing `solver=cvxpy.SCS` with `solver=cvxpy.MOSEK` will demonstrate the greater memory use.

**Expected behavior**
I would expect the problem compilation to not require that much memory.

**Output**
N/A

**Version**
 - OS: Ubuntu 22.04
 - CVXPY Version: 1.3.0

**Additional context**
Possibly related to #1011?

**Comment by rileyjmurray** [comment]
I'm pretty confident that using the MOSEK 10 interface will fix this.

**Comment by phschiele** [comment]
This is caused by the function [vectorized_lower_tri_to_triples](https://github.com/cvxpy/cvxpy/blob/2a23c109e49577d8da4b97bbf6c866400da105c4/cvxpy/reductions/solvers/conic_solvers/mosek_conif.py#L52). As [this comment](https://github.com/cvxpy/cvxpy/blob/2a23c109e49577d8da4b97bbf6c866400da105c4/cvxpy/reductions/solvers/conic_solvers/mosek_conif.py#L179-L181) suggests, it's a known inefficiency.  Since this is called when specifying PSD constraints, I'd agree that this will likely be fixed by the new interface.

The following gives a substantial speedup over the current implementation for the given example:
```py
    A = A_row.tocoo()
    vals = A.data
    flattened_cols = A.col
    cum_cols = np.cumsum(np.arange(dim, 0, -1))
    rows, cols = [], []
    current_col = 0
    for v in flattened_cols:
        for c in range(current_col, dim):
            if v <= cum_cols[c]:
                cols.append(c)
                prev_row = 0 if c == 0 else cum_cols[c - 1]
                rows.append(v - prev_row)
                break
            else:
                current_col += 1
```
@SteveDiamond @rileyjmurray Do you think it is still worth opening a PR for this improvement to the old interface?

**Comment by SteveDiamond** [comment]
Yes definitely.

**Comment by cohnt** [comment]
If it's as quick a fix as making that change, it would be extremely helpful to include it. Switching from MOSEK to SCS in the above example led to significantly poorer numerics, and required additional code to mitigate the issue.

**Comment by phschiele** [comment]
@cohnt @SteveDiamond Great, I can create a PR tomorrow.

**Comment by SteveDiamond** [comment]
We are blocked on a patch IMO by the deepcopy issue.

**Comment by rileyjmurray** [comment]
Ah, gotcha.

**Comment by cohnt** [comment]
This pull request seems to have solved the problem, and the example in the original post no longer has such a problem. So I'm gonna close the issue now.
