### ISSUE TITLE
ValueError: The denominator's sign must be known 

### ISSUE THREAD

**Issue by soga409** [cvxpy/cvxpy#2064]
**Describe the bug**
I was trying to solve a fractional optimization problem which turns out to be a DQCP.
After suceesfull reduction to a family of DCP problems for bisection, it Raised error:
ValueError("The denominator's sign must be known.")
Anyone knows what's wrong?

**To Reproduce**
import cvxpy as cp
cov_barra_f = np.random.rand(400,400)
cov_barra_f = cov_barra_f.T@cov_barra_f
ret_pred = np.ones(400)
thresh = 0.005
w = cp.Variable(len(ret_pred),pos = True)
ret = np.array(ret_pred) @ w
risk = cp.quad_form(w,cov_barra_f)
gamma = 500
prob = cp.Problem(cp.Maximize(ret/(gamma*risk)), [cp.sum(w) == 1, w>=0, w <= thresh])
prob.solve(qcp = True, verbose = True)

**Expected behavior**
prob.is_dqcp() is true and the prob is solvable by LFGBS(very slow when go to large dimension though). So I expect cvxpy should generate a result.

**Output**
ValueError                                Traceback (most recent call last)
<ipython-input-180-30b0db781d51> in <module>
      9 gamma = 500
     10 prob = cp.Problem(cp.Maximize(ret/(gamma*risk)), [cp.sum(w) == 1, w>=0, w <= thresh])
---> 11 prob.solve(qcp = True, verbose = True)
     12 

/home/anaconda3/lib/python3.8/site-packages/cvxpy/problems/problem.py in solve(self, *args, **kwargs)
    479         else:
    480             solve_func = Problem._solve
--> 481         return solve_func(self, *args, **kwargs)
    482 
    483     @classmethod

/home/anaconda3/lib/python3.8/site-packages/cvxpy/problems/problem.py in _solve(self, solver, warm_start, verbose, gp, qcp, requires_grad, enforce_dpp, ignore_dpp, **kwargs)
    997                 chain = Chain(problem=self, reductions=reductions)
    998                 soln = bisection.bisect(
--> 999                     chain.reduce(), solver=solver, verbose=verbose, **kwargs)
   1000                 self.unpack(chain.retrieve(soln))
   1001                 return self.value

/home/anaconda3/lib/python3.8/site-packages/cvxpy/reductions/reduction.py in reduce(self)
     92               "The reduction was constructed without a Problem.")
     93 
...
---> 68         raise ValueError("The denominator's sign must be known.")
     69 
  

**Version**
 - OS: Linux
 - CVXPY Version: 1.2.0

**Additional context**

**Comment by aszekMosek** [comment]
Is this actually the problem you want to solve or just a simplification of something more complicated you were working on? Because the problem itself can be easily formulated as DCP

```
import cvxpy as cp
import numpy as np
n=400
cov_barra_f = np.random.rand(n,n)
ret_pred = np.ones(n)
thresh = 0.005
w = cp.Variable(n)
prob = cp.Problem(cp.Minimize(cp.quad_over_lin(cov_barra_f@w, ret_pred@w)), [cp.sum(w) == 1, w>=0, w <= thresh])
prob.solve(verbose = True)
```

(note that my ``cov_barra_f`` is the factor, ie. the original one before doing ``A.T@A``, in other words I am using ``quad_form(w,A.T@A) = sum_squares(A@w)``, I minimize ``x/y`` instead of maximizing ``y/x`` and I skipped ``gamma`` which only rescales the objective).

**Comment by soga409** [comment]
> Is this actually the problem you want to solve or just a simplification of something more complicated you were working on? Because the problem itself can be easily formulated as DCP
> 
> ```
> import cvxpy as cp
> import numpy as np
> n=400
> cov_barra_f = np.random.rand(n,n)
> ret_pred = np.ones(n)
> thresh = 0.005
> w = cp.Variable(n)
> prob = cp.Problem(cp.Minimize(cp.quad_over_lin(cov_barra_f@w, ret_pred@w)), [cp.sum(w) == 1, w>=0, w <= thresh])
> prob.solve(verbose = True)
> ```
> 
> (note that my `cov_barra_f` is the factor, ie. the original one before doing `A.T@A`, in other words I am using `quad_form(w,A.T@A) = sum_squares(A@w)`, I minimize `x/y` instead of maximizing `y/x` and I skipped `gamma` which only rescales the objective).

Doing a QR decomposition is a great idea. Actually  my risk is cp.sqrt(w.T@cov_barra_f@w) and I want to maximize (ret_pred@w/cp.sqrt(w.T@cov_barra_f@w)).  This doesn't seems convex to me.

**Comment by aszekMosek** [comment]
@soga409 That is even easier in some sense, by homogenization. See https://docs.mosek.com/modeling-cookbook/cqo.html#maximizing-the-sharpe-ratio and let me know if you need more details.

**Comment by soga409** [comment]
@aszekMosek  Thanks for your help. I tried both Conic Programing and QuasiConvex programing. They both worked now. After homogenization, The problem takes much longger than I expected. It took me around 5 mins when I dealt with around 1700 stocks. I might want to deal with like 4000 stocks in the future, do you have any suggestions to speed up?
Here is my code:
```
import cvxpy as cp
ret_pred = ret_pred.loc[stock_list_barra]
thresh = 0.005
t = cp.Variable(1)
y = cp.Variable(len(ret_pred),pos = True)
r = np.linalg.qr(cov_barra_f)[1]     
prob = cp.Problem(cp.Minimize(t), [t >= cp.norm(r@y), np.array(ret_pred)@y ==1, y <= thresh* cp.sum(y)])
prob.solve(verbose = True)
```

**Comment by aszekMosek** [comment]
@soga409 You want ``linalg.cholesky`` and not ``linalg.qr``. You must have ``cov=A.T@A`` so that ``x.T@cov@x = norm(A@x)``.

5 minutes seems way too long. This is a fairly standard problem that normally should be solved at most in seconds. Maybe you should investigate the log to see what takes so long and perhaps use a different solver. Hard to say without seeing your full run.

If you have a factor model then you can exploit that not to compute and then factor the full dense covariance matrix, and then typically get an extremely efficient model. See https://docs.mosek.com/portfolio-cookbook/factormodels.html and the factor model section of https://colab.research.google.com/github/cvxgrp/cvx_short_course/blob/master/applications/portfolio_optimization.ipynb#scrollTo=em0pOINs10U8

Maybe the discussion should continue elsewhere. This does not look like an issue with cvxpy. For example I can invite to https://groups.google.com/g/mosek
