### ISSUE TITLE
CVXPY does not support log function.

### ISSUE THREAD

**Issue by SightVanish** [cvxpy/cvxpy#2074]
I try to use 'cp.log'. 
Here is the bug report I received:
```shell
cvxpy.error.DQCPError: The problem is not DQCP.
```

What can I do to fix this problem?

Here is my code:
```python
import numpy as np
import cvxpy as cp
n = 10
np.random.seed(3)
a = np.random.randint(1, 10, size=n)
b = np.random.randint(1, 10, size=n)

# print(a, b)

# Variables
x = cp.Variable(shape=n, boolean=True)
t = cp.Variable(shape=1)
# Objective
objective = cp.Maximize(t)
# Constraints
constraints = []
constraints.append(t + cp.log(x @ b) <= cp.log(x @ a))

# Build & Solve Problem
problem = cp.Problem(objective, constraints)
problem.solve(qcp=1)

# Print Result
print(problem.status)
print("x: ", x.value)
print("Optimal value: ", problem.value)
```

**Comment by Transurgeon** [comment]
Hello, please refer to the documentation (I have included an image below)
<img width="685" alt="image" src="https://user-images.githubusercontent.com/89562186/227665674-64ff3755-62fb-48a6-8327-ee1d421433fb.png">

Since we know that log(x) is a concave function, your objective fits the requirement. 
However your constraint seems to be (quasi)concave <= (quasi)concave, which isn't a valid DQCP constraint. 
(I could be wrong, but I think this makes sense as log is clearly concave and hence quasi-concave too).

**Comment by SightVanish** [comment]
> be (quasi)concave <= (quasi)concave, which isn't a valid DQCP constraint.
> (I could be wrong, but I think this makes sense as log is clearly concave and hence

You are right `log <= log` does not satisfy DQCP rules. Tks for reply.
