### ISSUE TITLE
Get the detailed solver call after cvxpy compilation

### ISSUE THREAD

**Issue by Wongboo** [cvxpy/cvxpy#2106]
I'm trying to get the detailed solver call code used by `cvxpy` after compilation, which means I wanna the code to bypass CVXPY and call the solver directly.
CVX documentation in chapter `Advanced Features` section `Getting the standard form` provides an example for `SCS`, for other solver, it guides with 'print data dict', which does not contain the solver call code only the data of problem.

**Comment by Wongboo** [comment]
No, I just want to print the code `cvxpy` using to invoke solver after compilation.

**Comment by phschiele** [comment]
@Wongboo Here is the code that gets executed after the problem data is obtained:
https://github.com/cvxpy/cvxpy/blob/a6e88643570c3b4852d62d5932ba3db7c2b10bd9/cvxpy/problems/problem.py#L1063-L1077

You might want to look at https://github.com/cvxgrp/cvxpygen. If your problem is DPP, it allows you to generate C code to directly interface with the solver and optionally also outputs Python bindings!

**Comment by Wongboo** [comment]
@phschiele Thanks, trying to use `cvxpygen`, though its solver support seems to be very limited.
