### ISSUE TITLE
conda install of 1.5.1 not detected by pip

### ISSUE THREAD

**Issue by pluflou** [cvxpy/cvxpy#2447]
**Describe the bug**
There is a bug in the packaging of v1.5.1. Pip fails to detect it when installed with conda; it seems to be missing the dist-info directory.

**To Reproduce**
In a fresh conda environment, install the latest cxvpy:
`conda install cvxpy -c conda-forge `

**Expected behavior**
I expect to see cvxpy listed as installed when calling `pip list` or `pip freeze`. 

**Output**
cvxpy shows up as `UNKNOWN` when calling `pip list` or `pip freeze`:
```bash
(test-pip) smiskov@PC99612 cvxpy % pip list
Package         Version
--------------- -----------
build           1.2.1
clarabel        0.7.1
ecos            2.0.13
numpy           1.26.4
osqp            0.6.3
packaging       24.0
pip             24.0
pyproject_hooks 1.1.0
qdldl           0.1.7.post2
scipy           1.13.0
scs             3.2.4.post1
setuptools      69.5.1
UNKNOWN         1.5.1
wheel           0.43.0
```

**Version**
 - OS: macOS 14.4.1 and Ubuntu 22.04.4
 - CVXPY Version: 1.5.1

**Additional context**
This was working as expected in v1.4.3. We saw this bug when building our conda package that depends on cvxpy. The build fails to pass the pip check test in our conda recipe (see workflow failure [here](https://github.com/cvxgrp/spcqe/actions/runs/9100537427/job/25015611547#step:6:311) and PR [here](https://github.com/cvxgrp/spcqe/pull/7)).

**Comment by pluflou** [comment]
@phschiele this is in relation to the bug we saw when building spcqe a couple days ago

**Comment by phschiele** [comment]
@pluflou I am able to reproduce your output on a fresh code space:

```
Package    Version                                                                                                                                                                                       
---------- -----------                                                                                                                                                                                   
clarabel   0.7.1                                                                                                                                                                                         
ecos       2.0.13                                                                                                                                                                                        
numpy      1.26.4                                                                                                                                                                                        
osqp       0.6.3                                                                                                                                                                                         
pip        24.0                                                                                                                                                                                          
qdldl      0.1.7.post2                                                                                                                                                                                   
scipy      1.13.0                                                                                                                                                                                        
scs        3.2.4.post1                                                                                                                                                                                   
setuptools 69.2.0                                                                                                                                                                                        
UNKNOWN    1.5.1                                                                                                                                                                                         
wheel      0.43.0   
```

Installing from PyPI works, though. 
@h-vetinari have you seen this behaviour before?

**Comment by h-vetinari** [comment]
> have you seen this behaviour before?

No I haven't...

We didn't change anything about the way cvxpy gets installed [between](https://github.com/conda-forge/cvxpy-feedstock/pull/90) 1.4.3 and 1.5.1 (the `stdlib` things are unrelated), so at a guess this would be something to do with some potential behaviour changes in pip/setuptools?

I added a test in https://github.com/conda-forge/cvxpy-feedstock/pull/92 and could reproduce the failure. On a hunch, I restricted to `pip <24`, but that didn't change anything. Note that we're deleting `pyproject.toml` before installation, because the way it is set up forces installation of
https://github.com/cvxpy/cvxpy/blob/f0986293c04be1f9bec1129aa4e52354ae8b2e01/pyproject.toml#L26-L34
which cannot work in conda-forge for various reasons (these packages get installed through conda before the build starts).

However, we've been doing that since a long time, so I don't think this should play a role here.

**Comment by h-vetinari** [comment]
@timkpaine found the issue - it's that `name="cvxpy"` is missing from `setup.py` since https://github.com/cvxpy/cvxpy/commit/d8f74ec152e4ca4b7381d339e9de0004df89beee.  In principle, this information is now present in pyproject.toml, but as I had mentioned, we removed that (mostly because it became painful to constantly patch out the build system).

**Comment by timkpaine** [comment]
It should be safe to include `name` in both since its obviously not going to change
