### ISSUE TITLE
Audit code for use of list comprehensions where generators would be faster

### ISSUE THREAD

**Issue by rileyjmurray** [cvxpy/cvxpy#2464]
While working on another Python project I noticed lots of code that used list comprehensions when [generators](https://peps.python.org/pep-0289/) would have sufficed. Generators are faster than list comprehensions and should be preferred in most situations.

I ran a quick search for string patterns which can match inefficient use of list comprehensions. Note that these string patterns might correspond to invocations of cvxpy functions that actually want lists and not generators.
* 2 calls to ``all([``
* 6 calls to ``any([``
* 17 calls to ``sum([``
* 2 calls to ``set([``

It shouldn't take someone more than 10 or 15 minutes to fix all of these. It might not impact performance, but worst-case scenario it improves our code hygiene.

**Comment by rileyjmurray** [comment]
Turns out that life isn't so simple. A colleague of mine on the other project did some profiling and found that no clear runtime advantage for generators over list comprehensions (in fact, he found there was a ~30% disadvantage to generators on Python 3.9). We haven't looked into memory usage yet but I suspect this is minor for cvxpy. So I'l just close this issue for now. Anyone who stumbles upon this GitHub issue is welcome to leave their thoughts as a comment.

**Comment by phschiele** [comment]
@rileyjmurray one thing that might be relevant:
A generator might be useful for `all` or `any` because you can short circuit.

The check and the fix can be carried out automatically by `ruff` when the "C4" ruleset is included.
The relevant rule is this one:
https://docs.astral.sh/ruff/rules/unnecessary-comprehension-in-call/

Gotchas are:
- some runtime overhead in terms of speed (in line with the excellent investigation of @coreyostrove)
- if you rely on side effects of operations within the list comprehension (which you shouldn't), the short-circuiting may prevent those from being carried out
