### ISSUE TITLE
QP problem - different solution with CLARABEL and OSQP

### ISSUE THREAD

**Issue by vladimirvrabely** [cvxpy/cvxpy#2554]
Hi,

when trying to solve this QP problem
```pythonimport cvxpy as cp
import numpy as np

m = [10_000, 10_000, 10_000, 10_000]
s = [0.4, 0.6, 0.9, 0.1]
weights = [20_000, 20_000, 20_000, 20_000]
dt = 15.0/60
n = len(m)

x = cp.Variable(n)
total_m = 30_000
constraints = [
    0 <= x,
    x <= m,
    cp.sum(x) == total_m,
]

objective = cp.sum_squares(s + x * dt / weights - 0.5)

problem = cp.Problem(cp.Minimize(objective), constraints)

for solver in [cp.CLARABEL, cp.OSQP]:
    print(f"SOLVER: {solver}")
    problem.solve(solver=solver)
    print(f"{problem.value = }")
    print(f"{problem.status = }")
    # print(f"{problem.solver_stats = }")
    print(f"{np.round(x.value, 1) = }")
```
I get these solutions
```
SOLVER: CLARABEL
problem.value = 0.28687500022009166
problem.status = 'optimal'
np.round(x.value, 1) = array([10000., 10000.,     0., 10000.])
SOLVER: OSQP
problem.value = 0.3743074440687389
problem.status = 'optimal'
np.round(x.value, 1) = array([7510., 7490., 7460., 7540.])
```
It seems that CLARABEL was able to find a better solution on the boundary. Is this an expected behaviour?

**Comment by aszekMosek** [comment]
The square ``(dt/weights)**2`` is of order 1e-10 so the quadratic coefficients in the QP representation of the problem basically disappear. You can see that if you solve for the objective `` cp.sum_squares(np.array(s) - 0.5)`` you will get almost the same answer.

Conic solvers do not show this behavior because for them in conic form the expression inside ``sum_squares`` is passed directly in its affine form, so the smallest coefficients are only of order ``dt/weights``, that is 1e-5.

So I would argue that your problem is just too badly scaled when cast as a QP: the quadratic coefficients are vanishingly small. The solution would be to rescale your ``m,total_m,weights,x`` down by 1e+3 or so (that would be a beneficial and reasonable modeling strategy regardless of solver).

**Comment by vladimirvrabely** [comment]
Oh, indeed. Thank you for quick response.
