### ISSUE TITLE
Continuous performance monitoring

### ISSUE THREAD

**Issue by akshayka** [cvxpy/cvxpy#705]
It would be really great if we set up continuous performance monitoring, so we could easily check for regressions. This monitoring infrastructure would just run the benchmarks in `cvxpy/tests/test_benchmarks.py`, for every commit, and record the timings. Ideally it would maintain one plot for each benchmark in test_benchmarks.py, with the x-axis being commit number and the y-axis being time.

**Comment by AtsushiSakai** [comment]
@akshayka Hi. First of all. Thank you for developing the great OSS, cvxpy. I love it. 

I'm interested in this issue.  I would like to help this project.

I created a OSS for benchmarking cvxpy.
AtsushiSakai/cvxpy_benchmark: Benchmark for cvxpy https://github.com/AtsushiSakai/cvxpy_benchmark

This is based on [airspeed velocity](https://asv.readthedocs.io/en/stable/index.html) which is a Python library for benchmarking.

This cvxpy_benchmark is setted up for cvxpy, and you can measure the calculation time with the benchmarks in cvxpy/tests/test_benchmarks.py, and creating a web based report automatically.

This is a sample report of the benchmarks in github-pages, please take a look: https://atsushisakai.github.io/cvxpy_benchmark/
(I don't do benchmarks for all commits yet, because it needs a lot of time to do it.)

If you like this benchmarking system, let me know. 
I would like to discuss with you to improve this benchmarking system.

Best

**Comment by rileyjmurray** [comment]
@akshayka is this issue the preferred place to suggest possible benchmarks? If not, should we create another issue, or a "Project"?

**Comment by akshayka** [comment]
@AtsushiSakai Sorry for the late response! I just took a look at your set-up --- it's great! This is the first I've heard of airspeed velocity, thanks for introducing me to it!

I'd be happy to discuss the design further, if you're still interested.

**Comment by AtsushiSakai** [comment]
@akshayka Hi. Thank you for your interest. The only thing we have to do is setuping a workflow for benchmarks. The prototype system is just doing benchmarks manually in my laptop, but I think automatic benchmarks would be better. 

Do you have a server or VPS node for the benchmarks? 
Or we can do the benchmarks on Travis CI, GitHub actions, or Circle CI etc.

**Comment by SteveDiamond** [comment]
Done!
