### ISSUE TITLE
Update kl_div documentation

### ISSUE THREAD

**Issue by robdmc** [cvxpy/cvxpy#733]
**Describe the bug**
There is a discrepancy in the mathematical definition cvxpy uses for kl_div

https://www.cvxpy.org/api_reference/cvxpy.atoms.elementwise.html#kl-div

and the standard mathematical definition, which wikipedia embraces.
https://en.wikipedia.org/wiki/Kullback%E2%80%93Leibler_divergence

There might be some numerical trickery you guys are using that is unfamiliar to me, but it's really not obvious to me how the two expressions are equivalent. 

I posted a similar question to your forum, but given it's possible this is a bug, I thought I'd raise it here as well.

**To Reproduce**
In numpy syntax where x and y are 1-d arrays, the standard expression for KL Divergence
is

D = sum(x * log(x / y))

In your implementation this expression would be

D = sum(kl_div(x, y)) = sum(x * log(x / y) - x + y)

Unless I'm missing something, those don't appear to be the same thing.

**Comment by rileyjmurray** [comment]
There is a subtle distinction between "[KL divergence](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.kl_div.html)" and "[relative entropy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.rel_entr.html#scipy.special.rel_entr)" in scientific python code. CVXPY follows the convention of SciPy. Most references in mathematics do not mention this difference, because these two functions are the same if you sum over their outputs, and the input vectors ``x``, ``y`` are probability distributions.


You might say that ``kl_div`` is a little awkward compared to ``rel_entr``, and honestly I'd agree with you there. However from an optimization perspective, ``kl_div`` makes more sense, because it is the perspective of the [convex conjugate](https://en.wikipedia.org/wiki/Convex_conjugate) of the exponential function. For this reason (and the simple fact that ``cvxpy.kl_div`` does exactly what the documentation says it does), I'm making this issue as resolved.

**Comment by robdmc** [comment]
Thanks so much for the explanation.  That makes sense.

**Comment by RylanSchaeffer** [comment]
I'm confused. Is the definition of KL divergence such as in the scipy documentation (https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.kl_div.html) consistent with Wikipedia's definition?

**Comment by RylanSchaeffer** [comment]
Another question. Does CVXPY have a relative entropy function? I couldn't find one here https://www.cvxpy.org/api_reference/cvxpy.atoms.elementwise.html

**Comment by rileyjmurray** [comment]
@RylanSchaeffer SciPy's definition of KL divergence is not consistent with Wikipedia, unfortunately. Wikipedia says that KL divergence and relative entropy are two names for the same thing. SciPy does have a `rel_entr`` function that is consistent with Wikipedia. I think SciPy is "in the wrong" here, but the stability of their API is too important to make a change at this point.

What we should do is add a ``rel_entr`` function to cvxpy that mimics the SciPy function. I'll create a new issue for that.

**Comment by RylanSchaeffer** [comment]
Can we also add this explanation to the documentation for KL divergence? I've been misusing the cvxpy function because of this...

**Comment by rileyjmurray** [comment]
Sure, @RylanSchaeffer. We can update documentation. Do you have suggestions for where we can add the clarification? The two places I see are in the docstring (autogenerates the web content https://www.cvxpy.org/api_reference/cvxpy.atoms.elementwise.html#kl-div) and maybe as an asterisk and footnote in [this table](https://www.cvxpy.org/tutorial/functions/index.html#elementwise-functions).

**Comment by RylanSchaeffer** [comment]
I think adding it to the docstring would be perfect, since the function definition is usually where I begin. How would you also feel about linking this issue? I don't know whether linking issues is inappropriate for documentation, but I'm sure if you add "This KL Divergence is different than the one in probability / information theory," other users will open issues asking for clarification. Maybe you want to nip that in the bud?

**Comment by rileyjmurray** [comment]
I think linking to this issue in the source code documentation is fine. Although, it's worth noting that ``cp.sum(cp.kl_div(p, q))`` is equal to the definition from information theory provided ``p,q >= 0`` and ``sum(p) == sum(q)``.
