### ISSUE TITLE
Build manylinux wheels

### ISSUE THREAD

**Issue by akshayka** [cvxpy/cvxpy#843]
We currently deploy wheels for macOS and Windows to pypi; it'd be awesome if we deployed manylinux wheels as well.

@rileyjmurray , I remember that you made some progress earlier (https://github.com/cvxgrp/cvxpy/pull/734). Can you document what else needs to be done, even if you don't have time to work on this right now?

**Comment by rileyjmurray** [comment]
Sorry for the delay Akshay. I did look into this at one point. The issue is that you can only build manylinux wheels on very old linux distributions (CentOS 6, for example). I was originally under the impression this meant we could not hope to deploy from Travis builds, so put the entire idea on hold.

But now reading more, it seems that it may not be too hard to do this with TravisCI. There is a demo project (https://github.com/pypa/python-manylinux-demo/blob/master/.travis.yml) which contains the main idea, at least when *only* building for linux.

The first step would be to determine how to have one or more of our Travis runs use the docker image like in the link I mentioned. I believe this could be done as a stand-alone step (i.e. no need to go all the way to building the wheels). I think the stumbling block here would be that we still want to build wheels for OSX, so ultimately we need to specify two different types of os-related build configurations. Right now we do that with the following segment of our .travis.yml file:
```
os:
  - osx
  - linux
```
The simultaneous management of OSX versus a docker image would likely be more complicated, but I'm sure it's doable.

Once we have docker builds working normally (just deploying for anaconda builds, and uploading a source distribution), then it would be reasonable to make changes to the deployment scripts with the goal of getting manylinux wheels deployed.

**Comment by bstellato** [comment]
Just to report on what we are doing with OSQP, we use [multibuild](https://github.com/matthew-brett/multibuild) at the repo [osqp-wheels](https://github.com/oxfordcontrol/osqp-wheels). 

It is not automatic from the release tag but we can handle different architectures and broken builds. If you upload by mistake a package on pypi that does not compile correctly on one architecture, it cannot be deleted. Using multibuild we can check if the wheels are correctly generated for all the platforms before manually uploading them to pypi. Not sure it is ideal for you but it is working for us.
